
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jenkins-lab

    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - DOCKER_HOST=tcp://dind:2375

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jcasc:/var/jenkins_home/casc_configs:ro

    depends_on:
      - dind

  dind:
    image: docker:27-dind
    container_name: jenkins-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    ports:
      - "2375:2375"
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
    volumes:
      - dind_storage:/var/lib/docker

volumes:
  jenkins_home:
  dind_storage:
